source "http://rubygems.org"

gem 'rake'
gem 'rack'
gem 'htmlentities'
gem 'jekyll', '>= 2.0.0'
gem 'rubypants'
gem 'rdiscount'
gem 'capistrano', '~> 2.15'
gem 's3-static-site'
gem 'nokogiri'
gem 'nokogiri-pretty'
gem 'indextank'
gem 'simple-cloudfront-invalidator'
gem 'japr', :git => 'git@github.com:brandonmwest/japr.git'
gem 'therubyracer'
gem 'less'
gem 'yui-compressor'
