source "http://rubygems.org"

gem 'rake'
gem 'jekyll', '~> 1.5.1'
gem 'rubypants'
gem 'rdiscount'
gem 'capistrano', '~> 2.15'
gem 's3-static-site'
gem 'nokogiri'
gem 'nokogiri-pretty'
gem 'indextank'
gem 'simple-cloudfront-invalidator'
gem 'japr'
gem 'therubyracer'
gem 'less'
gem 'yui-compressor'
