/* eslint quote-props: ["error", "consistent-as-needed"] */
const GROUPS = {
  'tracking-events': 'Tracking Events',
  'parsing-email': 'Parsing Email',
  'sending-email': 'Sending Email',
  'building-email': 'Building Email',
  'delivery-optimization': 'Delivery & Optimization',
  'troubleshooting': 'Troubleshooting',
  'platform-partners': 'Platform Partners',
  'tracking': 'Tracking',
  'managing-contacts': 'Managing Contacts',
  'building-your-list': 'Building Your List',
  'segmenting-your-list': 'Segmenting Your List',
  'stats-reporting': 'Statistics & Reporting',
  'statistics': 'Statistics',
  'click-tracking': 'Click Tracking',
  'email-activity': 'Email Activity Feed',
  'settings': 'Account Settings',
  'account-management': 'Account Management',
  'inbound-parse': 'Inbound Parse',
  'sender-authentication': 'Sender Authentication',
  'ip-management': 'IP Management',
  'teammates-subusers': 'Teammates & Subusers',
  'security': 'Security',
  'billing': 'Billing',
  'marketing-campaigns': 'Marketing Campaigns',
  'getting-started': 'Getting Started',
  'reference-troubleshooting': 'Reference & Troubleshooting',
  'code-examples': 'Code Examples',
  'partners': 'SendGrid Partners',
  'plugins': 'SendGrid Plugins',
  'smtp': 'SMTP API',
  'api-v2': 'SendGrid v2 API',
  'api-v3': 'SendGrid v3 API',
  'mail-servers': 'Mail Servers',
  'mail-clients': 'Mail Clients',
  'open-source': 'Open Source Apps',
  'ungrouped': 'Ungrouped'
};

export default GROUPS;